### ISSUE TITLE
-silent flag don't work properly

### ISSUE THREAD

**Issue by SamanSmini** [ImAyrix/fallparams#7]
fallparams -dir falldir -silent -o ssmammasdd

fallparams -dir falldir -silent > ssmammasdd

type these lines to view problem in tool

**Comment by ImAyrix** [comment]
I executed the exact command you provided, and the output was entirely correct. As I mentioned in the tool's documentation, using the -silent switch prevents banners and other non-essential information from being printed, displaying only the output. If by 'issue' you mean that the found parameters are being printed in the output, this is intentional and not a problem.

![Screenshot from 2024-08-25 09-19-35](https://github.com/user-attachments/assets/63ab921b-53d7-4469-9150-1c71a0e05f5c)

**Comment by ImAyrix** [comment]
Thanks for letting me know. The issue has been fixed, and you just need to update fallparams.

https://github.com/ImAyrix/fallparams/releases/tag/v1.0.12

**Comment by SamanSmini** [comment]
problem still exist !!!

**Comment by ImAyrix** [comment]
I have reviewed the issue and it appears to be resolved. I've attached a screenshot of the fallparams output below. If the problem persists, could you please let me know where you think the issue might still be?

![Screenshot from 2024-08-26 06-26-58](https://github.com/user-attachments/assets/ccb007c7-512e-4906-9b7b-970e7a7a6084)

**Comment by SamanSmini** [comment]
when i use -dir or -u flag:

on WSL2 ->

![image](https://github.com/user-attachments/assets/e5b0f49a-e164-4039-b6fe-89ec21d1db2b)

![image](https://github.com/user-attachments/assets/6187fd64-73fa-4aa9-923a-e505f9852aaf)


on Kali ->

![image](https://github.com/user-attachments/assets/54de8565-34b1-46f7-8f77-3004d2186f85)

![image](https://github.com/user-attachments/assets/1bab5b96-5e54-49f3-9375-bdb5151541db)


when i use ">" instead "-o" flag, problem solved:

![image](https://github.com/user-attachments/assets/96f6d767-677a-4db5-9128-8b7a24dd3433)

![image](https://github.com/user-attachments/assets/77adf1fb-7eb5-4263-b374-e826fb221104)

![image](https://github.com/user-attachments/assets/c55da0e4-34ad-4da3-8b0c-ba92bfabd096)

![image](https://github.com/user-attachments/assets/d1077164-11db-42aa-8a47-730d4f2f775c)


not important seriously
